# file: roles/wordpress/tasks/main.yml
#
# What to do to install and configure a WordPress instance
#
# Variables:: (in addition to those defined or documented in
#              ../vars/*.yml)

- name: Check whether WordPress is already installed
  stat:
    path: "{{ wp_path_config_php }}"
  register: _wp_config_php_stat

- include: delete.yml
  when: (inventory_hostname in wp_destructive_for) and (wp_destructive_action == "wipe")

- include: create.yml
  when: (inventory_hostname in wp_destructive_for) and ((wp_destructive_action == 'wipe') or (not _wp_config_php_stat.stat.exists))

- include: restore.yml
  when: false  # TODO

- name: Check whether WordPress is working
  command: wp --path={{ wp_dir }} eval '1;'
  changed_when: false

## Debug scaffolding #########################################
- name: Save facts (for debug)
  when: false  # That is, never
  local_action:
    module: copy
    content: "{{vars['ansible_facts'] | to_nice_json}}"
    dest: facts-{{inventory_hostname}}.json
- name: Save all variables (for debug)
  when: false  # That is, never
  local_action:
    module: copy
    content: "{{vars | to_nice_json}}"
    dest: vars-{{inventory_hostname}}.json
