# file: roles/wordpress/tasks/main.yml
#
# What to do to install and configure a WordPress instance
#
# Variables:: (in addition to those defined or documented in
#              ../vars/main.yml)
#
# - force_regenerate: Delete and recreate (from backup) this WordPress instance

- name: Check whether WordPress is working
  command: wp --path={{ wp_dir }} eval '1;'
  ignore_errors: yes
  register: wordpress_status

- include: delete.yml
  when: force_regenerate

- include: generate.yml
  when: "(wordpress_status.rc != 0) or (force_regenerate)"

- include: restore.yml
  when: "(wordpress_status.rc != 0) or (force_regenerate)"


## Debug scaffolding #########################################
- name: Save facts (for debug)
  when: false  # That is, never
  local_action:
    module: copy
    content: "{{vars['ansible_facts'] | to_nice_json}}"
    dest: facts-{{inventory_hostname}}.json
- name: Save all variables (for debug)
  when: false  # That is, never
  local_action:
    module: copy
    content: "{{vars | to_nice_json}}"
    dest: vars-{{inventory_hostname}}.json
