# Restore a WordPress site from backup

# Sanity checks - Will prevent damage, WILL NOT be helpful
# in debugging (the playbook cuts short while apparently successful)
- meta: end_play
  when: not (inventory_hostname in wp_destructive_for)
- meta: end_play
  when: wp_destructive_action == "none"

- name: TODO
  debug:
    msg: TODO
