# Restore a WordPress site from backup

- assert:
    that:
      - inventory_hostname in wp_destructive
      - wp_destructive[inventory_hostname] is search("data")
      - wp_restore_from is search("^backup")
  register: _sanitycheck_restore
- meta: end_play
  when: _sanitycheck_restore.failed

- include_vars: backup-vars.yml

- name: TODO
  debug:
    msg: TODO
