# file: roles/wordpress/vars/main.yml
#
# Define variables that this role relies on.
#
# Required per-host variables (typically coming out of hosts/group_vars/* and
# hosts/wordpress-instances):
#
#
# - wp_env: The name of the top-level directory (under the /srv of the
#            Openshift instance) where the server root resides
#
# - wp_hostname: The HTTP host name (fully qualified domain name) this
#                  WordPress is served under
#
# - wp_path: The path relative to the htdocs directory where the WordPress
#            instance is installed
#
# - wp_unit_name: The unit name
#
# - wp_unit_id: The unit ID
#
# Command-line variables:
#
# - wp_destructive_for: A list of WordPresses on which destructive action is
#                             permitted.

wp_destructive_for: []   # Default value

#
# - wp_destructive_action: One of "none" (the default), "wipe",
#                             "data-and-code" or "data-only". "wipe"
#                             means to completely and unconditionally
#                             delete everything; "data-and-code" and
#                             "data-only" allows performing restores
#                             (depending on the setting of
#                             wp_restore_from, below) for the
#                             corresponding assets. "none" means do
#                             no harm, yet doesn't rule out harmless
#                             mutations such as creating a WP site
#                             that does not yet exist.

wp_destructive_action: 'none'   # Default value

#
# - wp_restore_from: One of "generate" (the default), "backup-prod",
#                      or "none" to skip the restore process
#                      altogether and leave the destroyed /
#                      nonexistent WordPresses in whatever state they
#                      are currently in.

wp_restore_from: 'generate'

#
# Required facts:
#
# - ansible_remote_tmp: The directory for temporary files
#
# Exported Variables:: (See below)

# The environment variables required by the jahia2wp Python script
jahia2wp_env:
  WP_ENV: "{{wp_env}}"
  WP_VERSION: latest
  PYTHONPATH: "/srv/{{ wp_env }}/jahia2wp/src"
  # Required by jahia2wp generate and generate-many (lest we get
  # the wrong set of plugins)
  PLUGINS_CONFIG_BASE_PATH: ../data/plugins
  # Required by jahia2wp migrate-urls
  PYTHONIOENCODING: "utf-8"
  # Control where jahia2wp migrate-urls puts its temp files
  JAHIA2WP_VENT_TMP: "{{ansible_remote_tmp}}"

# The top-level directory of this WordPress instance
wp_dir: "/srv/{{ wp_env }}/{{ wp_hostname }}/htdocs/{{ wp_path }}"

# The path to the wp-config.php file
wp_path_config_php: "{{ wp_dir }}/wp-config.php"

# The directories where the jahia2wp.py tool resides
jahia2wp_dir: "/srv/{{ wp_env }}/jahia2wp"

# The URL that jahia2wp expects
jahia2wp_url:  "https://{{ wp_hostname }}/{{ wp_path }}"

# The things that one should send to the shell prior to running any
# jahia2wp command. Use like so:
#
# shell: {{ jahia2wp_shell }} generate --foo=bar ...
jahia2wp_shell: set -e; . {{ jahia2wp_dir }}/.env; export MYSQL_DB_HOST MYSQL_SUPER_USER MYSQL_SUPER_PASSWORD WP_ADMIN_USER WP_ADMIN_EMAIL; cd {{ jahia2wp_dir }}/src; {{ ansible_python_interpreter }} ./jahia2wp.py

# Whether to perform a delete/restore cycle on this WordPress instance.
# This is the default value (override with --extra-vars "force_regenerate=true")
force_regenerate: false

# The unit name. Override either on the command line with --extra-vars,
# or in the inventory file (../../../hosts/wordpress-instances)
wp_unit_name: "{{ wp_unit_id }}"
