# Ansible playbook for WordPress deployments

# "hosts" are not really hosts; rather, they are WordPress instances
# See the list in hosts/wordpress-instances
- hosts: all-wordpresses
  gather_facts: no   # Delayed, see below
  pre_tasks:
    - name: Ansible pre-configuration
      set_fact:
        ansible_user: www-data
        ansible_python_interpreter: "/srv/{{wp_env}}/venv/bin/python"
    - name: Create temporary directory
      tempfile:
        state: directory
        prefix: ansible-jahia2wp-
      register: tempfile
      changed_when: false
    - name: Use temporary directory
      set_fact:
        ansible_remote_tmp: "{{ tempfile.path }}"
    - name: Gathering facts (delayed after Ansible pre-configuration)
      setup:
  roles:
    - wordpress
